Found cached dataset amazon_reviews_multi (/home/lcur1101/.cache/huggingface/datasets/amazon_reviews_multi/en/1.0.0/724e94f4b0c6c405ce7e476a6c5ef4f87db30799ad49f765094cf9770e0f7609)
task  SA
self.device  cuda
  0%|          | 0/3 [00:00<?, ?it/s]100%|██████████| 3/3 [00:00<00:00, 29.14it/s]100%|██████████| 3/3 [00:00<00:00, 29.07it/s]
Traceback (most recent call last):
  File "/home/lcur1101/ATCS_group3/code/pipeline_file.py", line 217, in <module>
    acc = pipeline(LM_model, task, prompt_generator)
  File "/home/lcur1101/ATCS_group3/code/pipeline_file.py", line 106, in pipeline
    train_dataloader = create_dataloader(batch_size)
  File "/home/lcur1101/ATCS_group3/code/dataloaders.py", line 90, in create_dataloader
    sample_texts, sample_labels = marc_dataset.get_random_sample(
  File "/home/lcur1101/ATCS_group3/code/dataloaders.py", line 76, in get_random_sample
    with open(self.data_path, 'r', encoding='utf-8') as f:
AttributeError: 'MARCDataset' object has no attribute 'data_path'
srun: error: r36n2: task 0: Exited with exit code 1
